# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracaklasowa',
            name='przedmiot',
            field=models.CharField(default='', max_length=30),
        ),
    ]
